const CARDS = {
  "2D": "2D",
  "3D": "3D",
  "4D": "4D",
  "5D": "5D",
  "6D": "6D",
  "7D": "7D",
  "8D": "8D",
  "9D": "9D",
  "10D": "10D",
  JD: "JD",
  KD: "KD",
  QD: "QD",
  AD: "AD",
  "2H": "2H",
  "3H": "3H",
  "4H": "4H",
  "5H": "5H",
  "6H": "6H",
  "7H": "7H",
  "8H": "8H",
  "9H": "9H",
  "10H": "10H",
  JH: "JH",
  KH: "KH",
  QH: "QH",
  AH: "AH",
  "2S": "2S",
  "3S": "3S",
  "4S": "4S",
  "5S": "5S",
  "6S": "6S",
  "7S": "7S",
  "8S": "8S",
  "9S": "9S",
  "10S": "10S",
  JS: "JS",
  KS: "KS",
  QS: "QS",
  AS: "AS",
  "2C": "2C",
  "3C": "3C",
  "4C": "4C",
  "5C": "5C",
  "6C": "6C",
  "7C": "7C",
  "8C": "8C",
  "9C": "9C",
  "10C": "10C",
  JC: "JC",
  KC: "KC",
  QC: "QC",
  AC: "AC",
};
export const GAME_MODES = {
  MVSM: "Computador vs Computador",
  MVSH: "Computador vs Humano",
};
export const CARD_LIST = Object.keys(CARDS);

export const PHASE = {
  PreFlop: "PRE-FLOP",
  Flop: "FLOP",
  Turn: "TURN",
  River: "RIVER",
  End: "END",
};
export const PHASE_LIST = Object.keys(PHASE);
export const STRAGEGIES = { LIE: "LIE", THINK: "THINK" };

export const ACTIONS = {
  CALL: "CALL",
  FOLD: "FOLD",
  RAISE: "RAISE",
  BET: "BET",
  CHECK: "CHECK",
};
